# biz_server.toml

ver = "0.0.1"
#logPath = "/tmp/frontend.log"
serverId = 1

[server]
addr = "0.0.0.0:12345"

[syncRpcClient]
serviceName = "sync"
addr = "localhost:10002"

[bizRpcClient]
serviceName = "biz"
addr = "localhost:10001"

[authKeyRpcClient]
serviceName = "auth_key"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[authSessionRpcClient]
serviceName = "auth_session"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[[redis]]
name = "cache"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
dbNum = "0"
password = ""
